
export class Form {

  id?: number;              // Optional ID (auto-generated by the backend)
  firstName: string;        // Applicant's first name
  lastName: string;         // Applicant's last name
  email: string;            // Applicant's email address
  country: string;          // Applicant's country
  mobileNumber: number;     // Applicant's mobile number
  location: string;         // Applicant's location
  cv?: Blob | null;         // Applicant's CV (binary data, optional)
  adminId: number;          // The admin's ID (required, maps to `admin_id` in backend)

  constructor(
    firstName: string,
    lastName: string,
    email: string,
    country: string,
    mobileNumber: number,
    location: string,
    adminId: number,
    id?: number,             // Optional ID (used when fetching an existing form, if needed)
    cv?: Blob | null         // Optional CV file (if provided)
  ) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.country = country;
    this.mobileNumber = mobileNumber;
    this.location = location;
    this.adminId = adminId;
    if (id) this.id = id;
    if (cv) this.cv = cv;
  }
}
